// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VeterinariaGestion.Infrastructure.Data;

#nullable disable

namespace VeterinariaGestion.Infrastructure.Migrations
{
    [DbContext(typeof(VeterinariaDbContext))]
    [Migration("20260301024727_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idCliente");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("apellido");

                    b.Property<string>("CuilDni")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("cuildni");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("TEXT")
                        .HasColumnName("fechaAlta");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("telefono");

                    b.HasKey("IdCliente");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.CuentaCorriente", b =>
                {
                    b.Property<int>("IdCuentaCorriente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idCuentaCorriente");

                    b.Property<string>("Comprobante")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("comprobante");

                    b.Property<string>("Concepto")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("concepto");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("estado");

                    b.Property<string>("EstadoCuenta")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("estadoCuenta");

                    b.Property<DateTime?>("FechaMovimiento")
                        .HasColumnType("TEXT")
                        .HasColumnName("fechaMovimiento");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("TEXT")
                        .HasColumnName("fechaVencimiento");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("IdVenta")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("Importe")
                        .HasColumnType("TEXT")
                        .HasColumnName("importe");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("observacion");

                    b.Property<decimal>("SaldoAnterior")
                        .HasColumnType("TEXT")
                        .HasColumnName("saldoAnterior");

                    b.Property<decimal>("SaldoNuevo")
                        .HasColumnType("TEXT")
                        .HasColumnName("saldoNuevo");

                    b.Property<string>("TipoMovimiento")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo_movimiento");

                    b.HasKey("IdCuentaCorriente");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdVenta");

                    b.ToTable("CuentasCorrientes", (string)null);
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Cuota", b =>
                {
                    b.Property<int>("IdCuota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idCuota");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("estado");

                    b.Property<string>("EstadoCuota")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("estadoCuota");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("TEXT")
                        .HasColumnName("fechaPago");

                    b.Property<DateTime?>("FechaVencimiento")
                        .HasColumnType("TEXT")
                        .HasColumnName("fechaVencimiento");

                    b.Property<int>("IdVenta")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("InteresMora")
                        .HasColumnType("TEXT")
                        .HasColumnName("interesMora");

                    b.Property<decimal>("MontoCuota")
                        .HasColumnType("TEXT")
                        .HasColumnName("montoCuota");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("TEXT")
                        .HasColumnName("montoPagado");

                    b.Property<int>("NumeroCuota")
                        .HasColumnType("INTEGER")
                        .HasColumnName("numeroCuota");

                    b.Property<decimal>("SaldoPendiente")
                        .HasColumnType("TEXT")
                        .HasColumnName("saldoPendiente");

                    b.HasKey("IdCuota");

                    b.HasIndex("IdVenta");

                    b.ToTable("Cuotas", (string)null);
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Especie", b =>
                {
                    b.Property<int>("IdEspecie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idEspecie");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("estado");

                    b.HasKey("IdEspecie");

                    b.ToTable("Especies", (string)null);
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Historial", b =>
                {
                    b.Property<int>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idHistorial");

                    b.Property<string>("Diagnostico")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("diagnostico");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaConsulta")
                        .HasColumnType("TEXT")
                        .HasColumnName("fechaConsulta");

                    b.Property<int>("IdMascota")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_mascota");

                    b.Property<int?>("IdTurno")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_turno");

                    b.Property<string>("Indicacion")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("indicacion");

                    b.Property<string>("MotivoConsulta")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("motivoConsulta");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("observacion");

                    b.Property<DateTime?>("ProximoControl")
                        .HasColumnType("TEXT")
                        .HasColumnName("proximoControl");

                    b.Property<string>("Tratamiento")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("tratamiento");

                    b.HasKey("IdHistorial");

                    b.HasIndex("IdMascota");

                    b.HasIndex("IdTurno")
                        .IsUnique();

                    b.ToTable("Historial", (string)null);
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Mascota", b =>
                {
                    b.Property<int>("IdMascota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idMascota");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaNaci")
                        .HasColumnType("TEXT")
                        .HasColumnName("fechaNaci");

                    b.Property<int>("IdCliente")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_cliente");

                    b.Property<int>("IdEspecie")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_especie");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("Sexo")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("sexo");

                    b.HasKey("IdMascota");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEspecie");

                    b.ToTable("Mascotas", (string)null);
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idProducto");

                    b.Property<string>("Codigo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("codigo");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("estado");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_proveedor");

                    b.Property<int?>("IdTipo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_tipo");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<decimal>("PrecioMayorista")
                        .HasColumnType("TEXT")
                        .HasColumnName("precioMayorista");

                    b.Property<decimal>("PrecioMinorista")
                        .HasColumnType("TEXT")
                        .HasColumnName("precioMinorista");

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER")
                        .HasColumnName("stock");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdTipo");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Proveedor", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idProveedor");

                    b.Property<string>("CuilCuit")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("cuilCuit");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("estado");

                    b.Property<DateTime?>("FechaAlta")
                        .HasColumnType("TEXT")
                        .HasColumnName("fechaAlta");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("razonSocial");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("telefono");

                    b.HasKey("IdProveedor");

                    b.HasIndex("CuilCuit")
                        .IsUnique();

                    b.ToTable("Proveedores", (string)null);
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Tipo", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idTipo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("estado");

                    b.HasKey("IdTipo");

                    b.ToTable("Tipo", (string)null);
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Turno", b =>
                {
                    b.Property<int>("IdTurno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idTurno");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("estado");

                    b.Property<string>("EstadoTurno")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("estadoTurno");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha");

                    b.Property<string>("HoraTurno")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("horaTurno");

                    b.Property<int>("IdMascota")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_mascota");

                    b.Property<string>("Motivo")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT")
                        .HasColumnName("motivo");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("observacion");

                    b.HasKey("IdTurno");

                    b.HasIndex("IdMascota");

                    b.ToTable("Turnos", (string)null);
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idUsuario");

                    b.Property<int>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("activo");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<DateTime?>("FechaCreacion")
                        .HasColumnType("TEXT")
                        .HasColumnName("fechaCreacion");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombreUsuario");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("passwordHash");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Venta", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idVenta");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("TEXT")
                        .HasColumnName("descuento");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1)
                        .HasColumnName("estado");

                    b.Property<string>("EstadoPago")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("estadoPago");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha");

                    b.Property<string>("FormaPago")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("formaPago");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_cliente");

                    b.Property<string>("NumeroVenta")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("numeroVenta");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("observacion");

                    b.Property<decimal>("Recargo")
                        .HasColumnType("TEXT")
                        .HasColumnName("recargo");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("TEXT")
                        .HasColumnName("subTotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("TEXT")
                        .HasColumnName("total");

                    b.HasKey("IdVenta");

                    b.HasIndex("IdCliente");

                    b.HasIndex("NumeroVenta")
                        .IsUnique();

                    b.ToTable("Ventas", (string)null);
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.VentaDetalle", b =>
                {
                    b.Property<int>("IdVentaDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("idVentaDetalle");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cantidad");

                    b.Property<decimal>("DescuentoItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue(0m)
                        .HasColumnName("descuentoItem");

                    b.Property<int>("IdProducto")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_producto");

                    b.Property<int>("IdVenta")
                        .HasColumnType("INTEGER")
                        .HasColumnName("id_venta");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("TEXT")
                        .HasColumnName("precio_unitario");

                    b.Property<decimal>("SubTotalItem")
                        .HasColumnType("TEXT")
                        .HasColumnName("subTotalItem");

                    b.HasKey("IdVentaDetalle");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdVenta");

                    b.ToTable("Ventas_detalle", (string)null);
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.CuentaCorriente", b =>
                {
                    b.HasOne("VeterinariaGestion.Core.Entities.Cliente", "Cliente")
                        .WithMany("CuentasCorrientes")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeterinariaGestion.Core.Entities.Venta", "Venta")
                        .WithMany("CuentasCorrientes")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Cuota", b =>
                {
                    b.HasOne("VeterinariaGestion.Core.Entities.Venta", "Venta")
                        .WithMany("Cuotas")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Historial", b =>
                {
                    b.HasOne("VeterinariaGestion.Core.Entities.Mascota", "Mascota")
                        .WithMany("Historiales")
                        .HasForeignKey("IdMascota")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeterinariaGestion.Core.Entities.Turno", "Turno")
                        .WithOne("Historial")
                        .HasForeignKey("VeterinariaGestion.Core.Entities.Historial", "IdTurno")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Mascota");

                    b.Navigation("Turno");
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Mascota", b =>
                {
                    b.HasOne("VeterinariaGestion.Core.Entities.Cliente", "Cliente")
                        .WithMany("Mascotas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeterinariaGestion.Core.Entities.Especie", "Especie")
                        .WithMany("Mascotas")
                        .HasForeignKey("IdEspecie")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Especie");
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Producto", b =>
                {
                    b.HasOne("VeterinariaGestion.Core.Entities.Proveedor", "Proveedor")
                        .WithMany("Productos")
                        .HasForeignKey("IdProveedor")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VeterinariaGestion.Core.Entities.Tipo", "Tipo")
                        .WithMany("Productos")
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Proveedor");

                    b.Navigation("Tipo");
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Turno", b =>
                {
                    b.HasOne("VeterinariaGestion.Core.Entities.Mascota", "Mascota")
                        .WithMany("Turnos")
                        .HasForeignKey("IdMascota")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mascota");
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Venta", b =>
                {
                    b.HasOne("VeterinariaGestion.Core.Entities.Cliente", "Cliente")
                        .WithMany("Ventas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.VentaDetalle", b =>
                {
                    b.HasOne("VeterinariaGestion.Core.Entities.Producto", "Producto")
                        .WithMany("VentaDetalles")
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VeterinariaGestion.Core.Entities.Venta", "Venta")
                        .WithMany("Detalles")
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Cliente", b =>
                {
                    b.Navigation("CuentasCorrientes");

                    b.Navigation("Mascotas");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Especie", b =>
                {
                    b.Navigation("Mascotas");
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Mascota", b =>
                {
                    b.Navigation("Historiales");

                    b.Navigation("Turnos");
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Producto", b =>
                {
                    b.Navigation("VentaDetalles");
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Proveedor", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Tipo", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Turno", b =>
                {
                    b.Navigation("Historial");
                });

            modelBuilder.Entity("VeterinariaGestion.Core.Entities.Venta", b =>
                {
                    b.Navigation("CuentasCorrientes");

                    b.Navigation("Cuotas");

                    b.Navigation("Detalles");
                });
#pragma warning restore 612, 618
        }
    }
}
